//stdlib
#include <iostream> //standard i/O header
#include <cerrno> //global variable the kernel use to store the last error
#include <cstdlib>
#include <cstring>
#include <string_view>

//system
#include <sys/socket.h> 
#include <netinet/in.h>
#include <unistd.h> //used to handle file descriptors (read , write , close)
#include <cassert>
#include <poll.h>
#include <fcntl.h>

//STL
#include <vector>

const size_t k_max_msg = 32 << 20;  // likely larger than the kernel buffer


static void msg(const char *msg) {
    std::cerr << msg << std::endl;
}

static void msg_errno(const char *msg) {
    fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void die(const char *msg) {
    int err = errno;
    std::cerr << "[" << err << "] " << msg << std::endl; /*File Print Format: Unlike standard printf (which always prints to the screen), fprintf allows you to specify exactly where the text should be sent (to a file, a stream, or the screen).*/
    abort();
}


//Data structure to store the state information of each connection to use in the future
struct Conn {
    int fd = -1; //reference to the clients connnection file descriptor

    //to Store the application's intention for this event loop
    bool wantRead = false;
    bool wantWrite = false;
    bool wantClose = false;

    //buffered input and output
    std::vector<uint8_t> incoming; // data to be parsed by the application
    std::vector<uint8_t> outgoing; // responses generated by the application

};

//Non-Blocking Accept
static void fd_setNonBlock(int fd) {
    errno = 0;
    int flags = fcntl(fd , F_GETFL , 0);
    if(errno) {
        die("fctnl Error");
        return;
    }

    flags = flags | O_NONBLOCK; //set the non blocking  to true 
    /**
     * NOTE: we are using flags = flags | O_NONBLOCK here we are using a bitmasking method 
     * example flags = 010000 | 001100 = 011100 
     */
    errno = 0;
    (void)fcntl(fd , F_SETFL , flags);
    if (errno) {
        die("fcntl error");
    }
}



//accept new connection
static Conn *handleAccept(int fd) {
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(fd , (struct sockaddr*)&client_addr , &addrlen);

    if(connfd < 0) {
        msg_errno("accept() error");
        return NULL;
    } 

    uint32_t ip = client_addr.sin_addr.s_addr;
    fprintf(stderr, "new client from %u.%u.%u.%u:%u\n",ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, ip >> 24,ntohs(client_addr.sin_port));

    //set the new connection non blocking request mode
    fd_setNonBlock(connfd);

    //create the structure for the client
    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->wantRead = true; // read the 1st request (the client has to say first so that the server can serve)
    return conn;

}

//append the data to the buffer
static void bufAppend(std::vector<uint8_t> &buf , const uint8_t *data , size_t len) {
    buf.insert(buf.end() , data , data+len);
}

static void bufConsume(std::vector<uint8_t> &buf , size_t len) {
    buf.erase(buf.begin() , buf.begin()+len);
}

// process 1 request if there is enough data
static bool tryOneRequest(Conn *conn) {

    // tcp message packet has : [Header(sizeofthe message)| actual message of the size] 
    // 3. Try to parse the accumulated buffer.
    //check the message header
    if(conn->incoming.size() < 4) {
        return false; //means there is more data required so the the connection want to read more
    }

    //if the size of the message is available the extract is from the buffer
    uint32_t len = 0;
    memcpy(&len , conn->incoming.data() , 4);
    if(len > k_max_msg) { //size of the message is exceeding the message limit
        msg("too long");
        conn->wantClose = true;
        return false;
    }

    //check the message body
    if(4 + len > conn->incoming.size()) {
        return false; //our comple ip packet is not available with us so return false indicating that the connection wants to read more data
    }

    const uint8_t *request = &conn->incoming[4];

    //4. Process the parsed message
     // got one request, do some application logic
    printf("client says: len:%d data:%.*s\n",len, len < 100 ? len : 100, request);

    //generate the response
    bufAppend(conn->outgoing , (const uint8_t*)&len , 4);
    bufAppend(conn->outgoing , request , len);


    // 5. Remove the message from `Conn::incoming`. (to avoid proceeding 2nd time)
    bufConsume(conn->incoming , 4 + len);
    return true; //success

    
}

static void handleWrite(Conn *conn) {

    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd , conn->outgoing.data() , conn->outgoing.size());

    if (rv < 0 && errno == EAGAIN) {
        return; // actually not ready
    }
    if (rv < 0) {
        msg_errno("write() error");
        conn->wantClose = true;    // error handling
        return;
    }

    // remove written data from `outgoing`
    bufConsume(conn->outgoing ,  (size_t)rv);

    // update the readiness intention
    if(conn->outgoing.size() == 0) {
        conn->wantRead = true;
        conn->wantWrite = false;
    }
}

//handle the read request of clients
static void handleRead(Conn *conn) {

    //1.Do non blocking IO read
    uint8_t buf[64 * 1024]; //create a 64kb stack space to store the data temporarily
    size_t rv = read(conn->fd , buf , sizeof(buf));

    if (rv < 0 && errno == EAGAIN) {
        return; // actually not ready
    }
    // handle IO error
    if (rv < 0) {
        msg_errno("read() error");
        conn->wantClose = true;
        return; // want close
    }
    // handle EOF
    if (rv == 0) {
        if (conn->incoming.size() == 0) {
            msg("client closed");
        } else {
            msg("unexpected EOF");
        }
        conn->wantClose = true;
        return; // want close
    }
    // 2. Add new data to the `Conn::incoming` buffer.
    bufAppend(conn->incoming , buf , (size_t)rv);

    // 3. Try to parse the accumulated buffer.
    // 4. Process the parsed message.
    // 5. Remove the message from `Conn::incoming`.

    while (tryOneRequest(conn)) {}

    //// update the readiness intention

     if (conn->outgoing.size() > 0) {    // has a response
        conn->wantRead = false;
        conn->wantWrite = true;
        // The socket is likely ready to write in a request-response protocol,
        // try to write it without waiting for the next iteration.
        return handleWrite(conn);
    }   // else: want read
}


int main() {

            //socket(domain , conn-type , protocol)
    int fd = socket(AF_INET , SOCK_STREAM , 0);
     if (fd < 0) {
        die("socket()");
    }
    
    /*
        1.AF_INET is for IPv4. Use AF_INET6 for IPv6 or dual-stack sockets.
        2.SOCK_STREAM is for TCP. Use SOCK_DGRAM for UDP.
        3.The 3rd argument is 0 and useless for our purposes.
     */
    int val = 1;
    //int setsockopt(int sockfd, int level, int optname,const void optval[.optlen], socklen_t optlen);
    setsockopt(fd ,SOL_SOCKET, SO_REUSEADDR , &val, sizeof(val));

    //bind
    struct sockaddr_in addr = {}; //initiazlise a sockadder_in sturcture
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234); //htons converts the little endian representation to big endian 
    addr.sin_addr.s_addr = htonl(0); // wildcard IP 0.0.0.0
    
    int rv = bind(fd , (const struct sockaddr *)&addr , sizeof(addr));

    if(rv) {
        die("bind()");
    }

    //listen
    rv = listen(fd , SOMAXCONN);
    if(rv) {
        die("listen()");
    }

    std::cout << "Server is listening on port 1234..." << std::endl;

    //start the event loop

     // a map of all client connections, keyed by fd
     std::vector<Conn *> fd2conn; //On Unix, an fd is allocated as the smallest available non-negative integer, so the mapping from fd to Conn can be a flat array indexed by fd

     //the event loop
     std::vector<struct pollfd> poll_args;

     while(true) {

        poll_args.clear(); //It flushes old kernel answers and dead connections so you can build a completely fresh, accurate checklist for the next loop pass.

        // Register the listening socket (server socket bind) to watch for brand-new client connections
        struct pollfd pfd = {fd , POLLIN , 0}; //basically it tells the poll function to wake it when a new connection request comes

        poll_args.push_back(pfd);

        //insert all the existing connection to the poll list
        for(Conn *conn: fd2conn) {
            
            if(!conn) {
                continue; //if an index does not have a connection with it
            }

            struct pollfd pfd = {conn->fd , POLLERR , 0}; //POLLERR ->  Monitor the client socket for connection errors (broken pipes, crashes) by default 

            if(conn->wantWrite) {
                pfd.events = pfd.events | POLLOUT; //bitmasking techinque 
            }
            if(conn->wantRead) {
                pfd.events = pfd.events | POLLIN;
            }
            poll_args.push_back(pfd);
        }

        // wait for readiness (from the inserted connections)
        //nfds_t = unsigned int or long
        int rv = poll(poll_args.data() , (nfds_t)poll_args.size() , -1); // Tell the kernel to watch our sockets;  block indefinitely until an event occurs (Your thread goes to sleep here.)
        if(rv < 0 && errno == EINTR) {
            continue; //not an error
        }

        if(rv < 0) {
            die("POLL");
        }

        /**The sections below only runs when the poll signaled somthing */

        //Accept new connection requests (from the socket at zero index);
        if(poll_args[0].revents) { //revents is filled by the kernel when the client have something to say 

            //accept the new connection request and add it to the array by using the fd number as the index to access the connection
            Conn *conn = handleAccept(fd);

            if(conn) {
                //put the created connection into the map 
                if(fd2conn.size() <= (size_t)(conn->fd +1)) {
                    fd2conn.resize(conn->fd+1);
                }
                fd2conn[conn->fd] = conn;
            }
        }

        /**
         * 
                        THREAD STATUS
                            │
                            ▼
                ┌─────────────────────────┐
                │  poll(...) blocks!      │  ◄── Your thread goes to sleep here.
                │  (Zero CPU usage)       │      It stays here for seconds, hours, or days.
                └────────────┬────────────┘
                            │
                            │  (Kernel detects a client sent network data!)
                            ▼
                ┌─────────────────────────┐
                │  poll(...) wakes up     │  ◄── The kernel wakes your thread up.
                └────────────┬────────────┘
                            │
                            ▼
                ┌─────────────────────────┐
                │ for(size_t i = 1; ...)  │  ◄── THIS LOOP RUNS EXACTLY ONCE.
                │ (Processes active fds)  │      It sweeps through, handles the data, and finishes.
                └────────────┬────────────┘
                            │
                            ▼
                ┌─────────────────────────┐
                │ Loops back to top       │  ◄── Your thread immediately goes back to sleep
                │ and blocks on poll()    │      inside poll(), waiting for the next signal.
                └─────────────────────────┘
         */
        
     // handle connection sockets (serve the request by clients) 
        for(size_t i = 1 ; i < poll_args.size() ; i++) {

            uint32_t ready = poll_args[i].revents;
            Conn *conn = fd2conn[poll_args[i].fd];

            if(ready & POLLIN) { //& is used to find the condition from the bit masking
                handleRead(conn); //application logic
            }
            if(ready & POLLOUT) {
                handleWrite(conn); //application logic
            }

            if((ready & POLLERR) || conn->wantClose) {
                (void)close(conn->fd);
                fd2conn[conn->fd] = nullptr;
                delete conn;
            }
        }

         
        


    }
    return 0;

}