//stdlib
#include <iostream> //standard i/O header
#include <cerrno> //global variable the kernel use to store the last error
#include <cstdlib>
#include <cstring>
#include <string_view>

//system
#include <sys/socket.h> 
#include <netinet/in.h>
#include <unistd.h> //used to handle file descriptors (read , write , close)
#include <cassert>
#include <poll.h>
#include <fcntl.h>

//STL
#include <vector>

const size_t k_max_msg = 32 << 20;  // likely larger than the kernel buffer


static void msg(const char *msg) {
    std::cerr << msg << std::endl;
}

static void msg_errno(const char *msg) {
   std::cerr << "[Error No: " << errno << "] : " << msg << std::endl;
}

static void die(const char *msg) {
    int err = errno;
    std::cerr << "[" << err << "] " << msg << std::endl; /*File Print Format: Unlike standard printf (which always prints to the screen), fprintf allows you to specify exactly where the text should be sent (to a file, a stream, or the screen).*/
    abort();
}


//Data structure to store the state information of each connection to use in the future
struct Conn {
    int fd = -1; //reference to the clients connnection file descriptor

    //to Store the application's intention for this event loop
    bool wantRead = false; //Hey loop, I'm waiting for a new command. Please ask poll() to watch for POLLIN
    bool wantWrite = false; //Hey loop, I have unsent bytes trapped in my outgoing buffer. Please ask poll() to watch for POLLOUT
    bool wantClose = false; //Hey loop, I encountered a protocol violation or received an EOF. Please run the delete routine on me during the next cleanup sweep.

    //buffered input and output
    std::vector<uint8_t> incoming; // data to be parsed by the application
    std::vector<uint8_t> outgoing; // responses generated by the application
    //uint8_t = unsigned int of 8bits = 1bytes (0 - 255)range best for storing streamed data (char , image file , video);

};

static void bufAppend(std::vector<uint8_t> &buf , const uint8_t *data , size_t size){
    buf.insert(buf.end() , data , data+size); 
    /**
     *  buf.end() -> pointer to the position after the last available data in the vector
     *  data is the starting address of your raw data.

        data + size uses pointer arithmetic to calculate the ending boundary. In C++, range boundaries are always exclusive (meaning it copies everything up to, but not including, the exact address of data + size).
     */
}

static void bufConsume(std::vector<uint8_t> &buf , size_t n){
    buf.erase(buf.begin() , buf.begin()+n);
}

static bool tryOneRequest(Conn *conn) {
    //parse the protocol message header
    if(conn->incoming.size() < 4) { //message size not recived so return false that there is more data ro read
        return false;
    }

    uint32_t len = 0;
    memcpy(&len , conn->incoming.data() , 4);

    if(len > k_max_msg) {
        msg("Too long message");
        conn->wantClose = true;
        return false; //want to close
    }

    //check for the recived message
    if(conn->incoming.size() < len + 4) { // the data is incomplete there to more data to be recieved 
        return false;
    }

    const uint8_t *request = &conn->incoming[4];

    //print the message by clinet
    std::cout << "Client Want to say : ";
    std::cout.write(reinterpret_cast<const char*>(request), len);
    std::cout << std::endl;

    //gerate new response
    const uint8_t response[] = "Hello this is from the server";
    uint32_t newLen = sizeof(response);
    bufAppend(conn->outgoing , (const uint8_t*)&newLen , 4);
    bufAppend(conn->outgoing , response , newLen);

     // application logic done! remove the request message.
     bufConsume(conn->incoming , (size_t)(4+len));

     return true;
    
} 

//set the file descriptors in non blocking mode
static void fdSetNonBlock(int fd) {
    errno = 0;
    int flags = fcntl(fd , F_GETFL , 0);

    if(errno) {
        die("Fcntl Error");
        return;
    }

    flags = flags | O_NONBLOCK; //add the nonblock option using the bit masking

    errno = 0;
    (void)fcntl(fd , F_SETFL , flags);
        if(errno) {
        die("Fcntl Error");
    }
}

static Conn * handleAccept(int fd) {

    //accpt the incomming request
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(fd , (struct sockaddr*)&client_addr , &addrlen);
    if(connfd < 0) {
        msg_errno("accept() error");
        return NULL;
    }

    //print the clier ip address
    uint32_t ip = client_addr.sin_addr.s_addr; //this is stored in the little endian form
    std::cerr << "New Client IP : " 
          << (ip & 255) << "." 
          << ((ip >> 8) & 255) << "." 
          << ((ip >> 16) & 255) << "." 
          << (ip >> 24) << ":" 
          << ntohs(client_addr.sin_port) << std::endl;

    //set the new connection to be non blocking
    fdSetNonBlock(connfd);

    Conn *conn = new Conn();

    conn->fd = connfd;
    conn->wantRead = true; //at first the kernel should seek the data from the client 
    return conn;
    
}

static void handleWrite(Conn *conn) {
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd , conn->outgoing.data() , (size_t)conn->outgoing.size());

    if(rv < 0 && errno == EAGAIN) {
        return; //NOT AN Error
    }
    if (rv < 0) {
        msg_errno("write() error");
        conn->wantClose = true;    // error handling
    }  
    
    //consume the buffer after read
    bufConsume(conn->outgoing , (size_t)rv);

    if(conn->outgoing.size() == 0) { //all data is consumed
        conn->wantRead = true;
        conn->wantWrite = false;
        return;
    }
}

static void handleRead(Conn *conn) {

    uint8_t buf[64*1024]; //Create a 64KB slot on stack to store the recived data temporarily
    ssize_t rv = read(conn->fd , buf , (size_t)sizeof(buf));

    //if the read syscall returned an error
    if(rv < 0 && errno == EAGAIN) {
        return; //Resource Temporarily Unavailable (Try Again).
    }

    if(rv < 0) {
        msg_errno("read() Error");
        conn->wantClose = true;
        return;
    }
    if(rv == 0) {
        if(conn->incoming.size() == 0) {
            msg("Client Closed");
        } else {
            msg("Unexpected EOF");
        }

        conn->wantClose = true;
        return;
    }

    //Store the recieved data in a persistent storage (conn->incoming) 
    bufAppend(conn->incoming , buf , (size_t)rv);

    // TCP Stream Parser: A fast client might bundle multiple requests into a single read().
    // This loop aggressively extracts and handles every complete message frame back-to-back 
    // until the buffer is empty or holds an incomplete packet, preventing pipeline deadlocks.
    while(tryOneRequest(conn)) {}

    //update readiness information
    if(conn->outgoing.size() > 0) { //has a respose with it
        conn->wantRead = false;
        conn->wantWrite = true;
        
        //if the app has its response ready then directly send it to the client without waiting for the next round to come
        return handleWrite(conn);
    } //else : wantread = true;


}

int main() {

            //socket(domain , conn-type , protocol)
    int fd = socket(AF_INET , SOCK_STREAM , 0);
     if (fd < 0) {
        die("socket()");
    }
    
    /*
        1.AF_INET is for IPv4. Use AF_INET6 for IPv6 or dual-stack sockets.
        2.SOCK_STREAM is for TCP. Use SOCK_DGRAM for UDP.
        3.The 3rd argument is 0 and useless for our purposes.
     */
    int val = 1;
    //int setsockopt(int sockfd, int level, int optname,const void optval[.optlen], socklen_t optlen);
    setsockopt(fd ,SOL_SOCKET, SO_REUSEADDR , &val, sizeof(val));

    //bind
    struct sockaddr_in addr = {}; //initiazlise a sockadder_in sturcture
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234); //htons converts the little endian representation to big endian 
    addr.sin_addr.s_addr = htonl(0); // wildcard IP 0.0.0.0
    
    int rv = bind(fd , (const struct sockaddr *)&addr , sizeof(addr));

    if(rv) {
        die("bind()");
    }

     //set the listening socket (fd) as non block mode 
     fdSetNonBlock(fd);

    //listen
    rv = listen(fd , SOMAXCONN);
    if(rv) {
        die("listen()");
    }

    std::cout << "Server is listening on port 1234..." << std::endl;

    //start the event loop

    //1.Store all the connection fds in the conn container using an vector with fd as the index number
    /*Linux allocates the smallest available integer vairable to teh fd so it can be used as the array index*/
    std::vector<Conn *> fd2conn;

    std::vector<struct pollfd> pollArgs; 
    /*struct pollfd {
        int fd;	-> reference to the file descriptor 		
        short int events; -> POLLIN , POLLOUT , POLLERR	
        short int revents; -> filled by the kernel
    }*/

    while(true) {
        pollArgs.clear(); //first clear the old connection in case any connection is destroyed or closed that should also be removed

        //insert the listening socket to the zero index 
        struct pollfd pfd = {fd , POLLIN , 0}; //(basically it tells the poll function to wake it when a new connection request comes)
        pollArgs.push_back(pfd);

        //insert all the client connection to the poll
        for(Conn *conn : fd2conn) {

            if(!conn) {
                continue; 
            }

            struct pollfd pfd = {conn->fd , POLLERR , 0}; //POLLERR ->  Monitor the client socket for connection errors (broken pipes, crashes) by default 
            if(conn->wantRead) {
                pfd.events = pfd.events | POLLIN;
            }
            if(conn->wantWrite) {
                pfd.events |= POLLOUT;
            }
            pollArgs.push_back(pfd);
        }

        //now wait for the readiness of the sockets 
        int rv = poll(pollArgs.data() , (nfds_t)pollArgs.size() , -1); // Tell the kernel to watch our sockets;  block indefinitely until an event occurs (Your thread goes to sleep here.)
        if(rv < 0 && errno == EINTR) { // EINTR = Interrupted System Call
            continue;
        }
        if(rv < 0) {
            die("POLL()");
        }

        /**if we reached this line means one or more sockets have given the signal that they want to perform something these may be 
         * 1. The main listening socket placed in index 0 which indicate that new connection came 
         * 2. The Client sockets want to do some (read /write ) on our application
         */
        
         //1. Check if new connection request came
         if(pollArgs[0].revents) {

            //accept the new connection and generate a Conn object
            Conn *conn = handleAccept(fd);

            if(conn != NULL) {

                //put the connection opj to the map
                if(fd2conn.size() <= (size_t)conn->fd){
                    fd2conn.resize((size_t)conn->fd+1);
                }
                assert(!fd2conn[conn->fd]); //check that the slot is empty (means the slot is not allocated to any other active socket)
                fd2conn[conn->fd] = conn;

            }
         }

         //2. Now handle the event from the client sockets
         for(size_t i = 1 ; i < pollArgs.size() ; i++) {
            uint32_t ready = pollArgs[i].revents;
            if(ready == 0) {
                continue;
            }

            Conn *conn = fd2conn[pollArgs[i].fd];

            if(ready & POLLIN) {
                assert(conn->wantRead);
                handleRead(conn);
            }
            if(ready & POLLOUT) {
                assert(conn->wantWrite);
                handleWrite(conn);
            }

            // close the socket from socket error or application logic
            if((ready & POLLERR) || conn->wantClose) {
                (void)close(conn->fd);
                fd2conn[conn->fd] = NULL;
                delete conn;
            }
         }

    }
    
    return 0;

}
